export const HELP_TOPICS = [
  { id: 'home', title: 'Home and workforce overview', description: 'Start calmly at Home. Open detailed overview for dependency scores, risk tables and suggested actions.', keywords: ['welcome', 'dashboard'], faq: ['Where do I start after signing in? Choose a Home card.'], view: 'overview' },
  { id: 'heat-map', title: 'Skill map and heat map', description: 'Choose Network, Matrix, Heat map or Charts. Search skill names or categories, select a department and a minimum proficiency. At-risk only uses the organization-wide Bus Factor of zero or one.', keywords: ['coverage', 'skills', 'map'], faq: ['What do cells mean? Recorded qualified holders / organization target. Department cells compare a contribution with the organization target, not a department requirement.', 'Critical means zero recorded qualified holders with verified evidence. At risk means one holder or a gap below 80% of target. Watch means at least 80% but below target with two or more holders. Healthy meets target with two or more holders. Unknown means missing targets, missing evidence or unverified qualifying evidence.', 'Qualification uses the higher of the selected minimum and the skill target. No record is unknown, never proof that a person lacks a skill.'], view: 'network' },
  { id: 'export-skill-map', title: 'Exporting reports and skill-map CSV', description: 'In Skill map choose Download CSV. The server exports visible evidence matching skill search, department, minimum proficiency and At-risk only. An empty result cannot be downloaded.', keywords: ['export', 'download', 'excel', 'power bi', 'tableau'], faq: ['What is exported? Employee and skill identifiers, names, department, role, proficiency, verification, source, target, filtered qualified holders and organization dependency score.', 'Can I export everyone? Managers receive only their visible team; employees cannot export workforce skill maps. Export events are audited.'], view: 'network' },
  { id: 'key-people', title: 'Key people', description: 'See which skills depend on a person and the evidence behind possible backups. Dependency is not a prediction of departure.', keywords: ['people', 'employees', 'succession'], faq: [], view: 'people' },
  { id: 'planning', title: 'Time Machine', description: 'Model departures and development using scenarios. Scenarios never change official evidence.', keywords: ['simulation', 'planning'], faq: [], view: 'timemachine' },
  { id: 'advisor', title: 'AI advisor', description: 'Draft development and strategy proposals, then review them. Nothing becomes official without the existing approval workflow. This is separate from the local navigation assistant.', keywords: ['ai', 'development'], faq: [], view: 'ai' },
  { id: 'quality', title: 'Data quality', description: 'Review missing sources, stale evidence and other data issues. Acknowledge an issue with an owner or next step where permitted.', keywords: ['quality', 'verification'], faq: [], view: 'quality' },
  { id: 'reviews', title: 'Review queue', description: 'Submit evidence changes for review. Authorized reviewers approve or reject changes. You cannot approve your own submission.', keywords: ['approval', 'submission'], faq: [], view: 'reviews' },
  { id: 'audit', title: 'Audit history', description: 'Authorized readers can inspect the append-only history of sign-ins, evidence changes, reviews and exports.', keywords: ['history', 'audit', 'log'], faq: [], view: 'audit' },
  { id: 'users', title: 'Users and roles', description: 'Admins manage accounts, roles and access in Users & settings. HR and managers have their existing workforce and governance permissions. Employees see their own profile.', keywords: ['users', 'roles', 'admin', 'permissions', 'accounts'], faq: ['Why is a shortcut restricted? Your role does not allow that page. Ask an administrator about access.'], view: 'users' },
  { id: 'directory', title: 'Employee directory', description: 'Admins and HR add people, correct reporting lines and archive anyone who leaves. Archiving shows the impact first: reports to reassign, the sign-in that gets disabled and the skills that lose coverage. Archived people keep their history but leave every score.', keywords: ['directory', 'archive', 'add employee', 'new hire', 'leaver', 'reporting line', 'manager'], faq: ['Can I delete an employee? No. Archive keeps evidence and audit history while removing the person from coverage, teams and succession.', 'Can I undo an archive? Restore reactivates the record; a disabled sign-in must be re-enabled separately in Users & settings.'], view: 'directory' },
  { id: 'search', title: 'Global search', description: 'The search box in the top bar finds people, skills, roles, departments, risks, data-quality issues, saved scenarios, change requests and help topics. Every result is a link into the app. You only find what your role can already see.', keywords: ['search', 'find', 'lookup', 'jump'], faq: ['Why is a person missing from search? Managers only find their own team and employees only themselves; the name is not hidden by mistake.'] },
  { id: 'filters', title: 'Filters and saved views', description: 'Filters on the overview, key people, review queue, data quality, directory and accounts tables live in the page address, so a filtered page can be bookmarked or pasted to a colleague. Active filters show as chips; Reset clears them. Save view remembers a set of filters under a name, private to you.', keywords: ['filter', 'filters', 'saved view', 'saved views', 'chips', 'bookmark', 'share link', 'reset'], faq: ['Why is a table empty? The bar says how many records exist and that the filters excluded them; an empty list is not an all-clear.', 'Does a saved view store data? No. It stores filter values only and never results.'] },
  { id: 'suggestions', title: 'Suggested next steps', description: 'The overview lists safe actions drawn from data you can already see, each labelled by its basis: official, approved plan, pending, unverified or scenario. Suggestions never change data and never predict; dismiss the ones you have handled and restore them any time.', keywords: ['suggestions', 'next steps', 'recommendations', 'dismiss'], faq: ['Are suggestions AI? No. They are fixed rules over the same facts the pages show, so the same data always gives the same list.'], view: 'overview' },
  { id: 'notifications', title: 'Notifications', description: 'Use the bell in the top bar for relevant updates and follow its links to details.', keywords: ['bell', 'alerts'], faq: [] },
  { id: 'preferences', title: 'Language and theme settings', description: 'Use the preferences control before or after sign-in to choose English or Spanish and light, dark or system theme. Long-form guide content remains in English.', keywords: ['language', 'theme', 'dark', 'spanish', 'english'], faq: [] },
  { id: 'sessions', title: 'Security and session behavior', description: 'Keep me signed in on this device uses a persistent HTTP-only cookie. The server still applies idle and absolute expiration and immediate revocation. Clear the checkbox on shared devices and always sign out.', keywords: ['login', 'remember', 'password', 'caps lock', 'session', 'security'], faq: ['How long? Defaults are 8 hours idle and 24 hours absolute when selected. Unselected uses a browser-session cookie with an 8-hour maximum. Administrators can shorten these limits. Browser restore features may retain session cookies.', 'What if Caps Lock is on? A warning appears near the password field when the browser reports Caps Lock. Password text is never revealed.', 'What if sign-out fails? Retry when connected; the app does not claim the server session was cleared.'] },
  { id: 'assistant', title: 'Keystone Assistant', description: 'A local curated navigation helper explains basics and opens allowed pages. Questions stay in memory and are not sent to an external model, saved to browser storage or logged.', keywords: ['assistant', 'chat', 'help', 'guide'], faq: ['Can it make workforce decisions? No. Unsupported or specific workforce questions lead to the Help Center.'] },
];
export const searchHelp = (entries, query = '') => {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  return entries.filter((entry) => {
    const text = JSON.stringify(entry).toLowerCase();
    return words.every((word) => text.includes(word));
  });
};
