import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import React from 'react';
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/' });
globalThis.window = dom.window;
globalThis.document = dom.window.document;
Object.defineProperty(globalThis, 'navigator', { value: dom.window.navigator, configurable: true });
globalThis.HTMLElement = dom.window.HTMLElement;
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const { render, fireEvent, screen, waitFor, cleanup } = await import('@testing-library/react');
const server = await createServer({ server: { middlewareMode: true }, appType: 'custom' });
const { default: Login } = await server.ssrLoadModule('/src/components/Login.jsx');
const { authApi } = await server.ssrLoadModule('/src/api/keystone.js');
// The login fixture contains no usable credentials and never calls a server.
authApi.environment = async () => ({ environment: 'demo', organizationName: 'Test workspace' });
test.after(async () => { cleanup(); await server.close(); dom.window.close(); });
test('login defaults to persistence in demo, submits an explicit opt-out and renders Caps Lock accessibly', async () => {
  let submitted;
  const session = { user: { displayName: 'Test' } };
  let signedIn;
  authApi.login = async (_email, _password, persistent) => { submitted = persistent; return session; };
  render(React.createElement(Login, { onSignedIn: (value) => { signedIn = value; } }));
  const remember = screen.getByRole('checkbox', { name: 'Keep me signed in' });
  await waitFor(() => assert.equal(remember.checked, true));
  const password = screen.getByLabelText('Password');
  fireEvent.focus(password);
  const capsOn = new dom.window.KeyboardEvent('keydown', { bubbles: true, key: 'A' });
  Object.defineProperty(capsOn, 'getModifierState', { value: (key) => key === 'CapsLock' });
  fireEvent(password, capsOn);
  assert.equal(screen.getByRole('status').textContent, ' Caps Lock is on.');
  assert.equal(password.type, 'password');
  assert.equal(password.getAttribute('aria-describedby'), 'caps-lock-warning');
  fireEvent.blur(password);
  assert.equal(screen.queryByText('Caps Lock is on.'), null);
  fireEvent(password, capsOn);
  const capsOff = new dom.window.KeyboardEvent('keyup', { bubbles: true, key: 'CapsLock' });
  Object.defineProperty(capsOff, 'getModifierState', { value: () => false });
  fireEvent(password, capsOff);
  assert.equal(screen.queryByText('Caps Lock is on.'), null);
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'fixture@example.test' } });
  fireEvent.change(password, { target: { value: 'unusable-test-fixture' } });
  fireEvent.click(remember);
  fireEvent.click(screen.getByRole('button', { name: 'Sign in', exact: true }));
  await waitFor(() => assert.equal(signedIn, session));
  assert.equal(submitted, false);
  cleanup();
});
test('production defaults to an unselected checkbox and a rejected login clears its password', async () => {
  authApi.environment = async () => ({ environment: 'production', organizationName: 'Production test' });
  authApi.login = async () => { throw new Error('Email or password is incorrect.'); };
  render(React.createElement(Login, { onSignedIn: () => assert.fail('invalid login') }));
  await screen.findByText('Production test');
  assert.equal(screen.getByRole('checkbox', { name: 'Keep me signed in' }).checked, false);
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'fixture@example.test' } });
  fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'unusable-test-fixture' } });
  fireEvent.click(screen.getByRole('button', { name: 'Sign in', exact: true }));
  await screen.findByRole('alert');
  assert.equal(screen.getByLabelText('Password').value, '');
  cleanup();
});

test('App restores a saved session, retains it after failed sign-out, and returns to login after confirmed sign-out', async () => {
  dom.window.scrollTo = () => {};
  const { default: App } = await server.ssrLoadModule('/src/App.jsx');
  const { keystoneApi } = await server.ssrLoadModule('/src/api/keystone.js');
  const session = { user: { id: 99, displayName: 'Test Person', role: 'employee', roleLabel: 'Employee', employeeId: null }, capabilities: [], organization: { name: 'Test workspace', environment: 'demo' } };
  authApi.me = async () => session;
  authApi.environment = async () => ({ environment: 'demo' });
  keystoneApi.organization = async () => ({ name: 'Test workspace' });
  authApi.logout = async () => { throw new Error('offline'); };
  dom.window.location.hash = '/home';
  render(React.createElement(App));
  await screen.findByRole('heading', { name: 'Home', exact: true });
  assert.equal(screen.queryByRole('heading', { name: 'Sign in', exact: true }), null);
  fireEvent.click(screen.getByRole('button', { name: 'Sign out', exact: true }));
  await screen.findByRole('alert');
  assert.ok(screen.getByRole('heading', { name: 'Home', exact: true }));
  authApi.logout = async () => {};
  fireEvent.click(screen.getAllByRole('button', { name: 'Sign out', exact: true })[0]);
  await screen.findByRole('heading', { name: 'Sign in', exact: true });
  assert.equal(screen.queryByRole('heading', { name: 'Home', exact: true }), null);
  cleanup();
});
